local gs = require "gitsigns"
map("n", "<a-]>", function()
  gs.next_hunk()
end, { desc = "next hunk" })
map("n", "<a-[>", function()
  gs.prev_hunk()
end, { desc = "previous hunk" })
map("n", "ss", function ()
  gs.stage_hunk()
end, desc_opts "Stage hunk")
map("v", "ss", function ()
  gs.stage_hunk({vim.fn.line("."), vim.fn.line("v")})
end, desc_opts("Stage hunk"))
map({"v", "n"}, "su", function ()
  gs.undo_stage_hunk()
end, desc_opts "Undo stage hunk")
map({"v", "n"}, "sp", function ()
  gs.preview_hunk()
end, desc_opts "Preview hunk")
map("n", "<leader>gg", "<cmd>Git<CR>", desc_opts "Open Fugitive")
map("n", "<leader>gd", "<cmd>DiffviewOpen<CR>", desc_opts "Open Diffview for current cursor")
map("n", "<leader>gh", "<cmd>DiffviewFileHistory %<CR>", desc_opts "Open Diffview History for current file")
map("v", "<leader>gh", ":<C-u>'<,'>DiffviewFileHistory<CR>", desc_opts "Open Diffview History for current file")
map("n", "<leader>gH", "<cmd>DiffviewFileHistory<CR>", desc_opts "Open Diffview History for current file")
map("n", "<leader>go", "<cmd>DiffviewClose<CR>", desc_opts "Open Diffview for current cursor")
map("n", "<leader>gm", "<cmd>Merginal<CR>", desc_opts "Open Merginal")
map("n", "<leader>gj", "<cmd>GBrowse<CR>", desc_opts "Open GBrowse for current cursor")
map("v", "<leader>do", "<cmd>'<,'>diffget<CR>")
map("n", "<leader>db", "<cmd>Gitsigns toggle_current_line_blame<CR>", desc_opts "Toggle Current Line Blame")
local diff_func = function(opt)
  vim.cmd("tabnew %")
  require("gitsigns").diffthis(opt.base or "HEAD", opt)
  vim.cmd("windo set wrap")
end
local df_func = function()
  diff_func({ base = "HEAD" })
end
local dv_func = function()
  diff_func({ base = "HEAD", vertical = true })
end
map("n", "<leader>df", df_func, desc_opts "Diff this")
map("n", "<leader>dv", dv_func, desc_opts "Diff this")
map("n", "<leader>dz", "<cmd>Gitsigns toggle_linehl<CR>", desc_opts "Diff line")
map({ "o", "x" }, "ih", ":<C-U>Gitsigns select_hunk<CR>", desc_opts "GitSigns Select Hunk")
